"""Transparency label text shown to readers. Exact wording lives in
README.md "Transparency Label" section — keep these two in sync.
"""

LABEL_TEMPLATES = {
    "likely_ai": (
        "\U0001F916 Likely AI-Generated — Our system estimates a {pct}% "
        "likelihood that this content was generated by AI, based on "
        "language-model analysis and writing-style patterns. If you wrote "
        "this yourself, you can appeal this classification."
    ),
    "likely_human": (
        "✍️ Likely Human-Written — Our system estimates a {pct}% "
        "likelihood that this content was written by a human, based on "
        "language-model analysis and writing-style patterns. No action is "
        "needed."
    ),
    "uncertain": (
        "❓ Uncertain Origin — Our system could not confidently "
        "determine whether this content was written by a human or AI "
        "(AI-likelihood: {pct}%). This reflects genuine uncertainty, not "
        "suspicion of wrongdoing."
    ),
}


def render_label(attribution: str, combined_score: float) -> str:
    # combined_score is P(AI). For the human-facing label, "likely_human"
    # and "uncertain" should quote confidence in *their own* direction,
    # not raw P(AI) — e.g. a 0.13 P(AI) score is "87% likely human," not
    # "13% likely human."
    if attribution == "likely_human":
        pct = round((1 - combined_score) * 100)
    else:
        pct = round(combined_score * 100)
    return LABEL_TEMPLATES[attribution].format(pct=pct)
