"""LLM-based detection signal using Groq (llama-3.3-70b-versatile).

Asks the model to holistically judge whether a passage reads as
AI-generated. Captures semantic/stylistic coherence that the stylometric
signal cannot see. See planning.md, "Detection Signals -> Signal 1".
"""

import json
import os
import re

from groq import Groq

MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = (
    "You are a careful literary analyst helping a creative-writing platform "
    "assess content provenance. Read the passage and judge whether it was "
    "likely written by a human or generated by an AI language model. Look "
    "for things like generic hedging, overly balanced framing, formulaic "
    "transitions, lack of a specific personal point of view, or unnaturally "
    "even pacing. Respond with ONLY a JSON object, no other text, in this "
    'exact shape: {"ai_probability": <float between 0 and 1>, "reasoning": '
    '"<one short sentence>"}'
)

_JSON_RE = re.compile(r"\{.*\}", re.DOTALL)


def _get_client() -> Groq:
    api_key = os.environ.get("GROQ_API_KEY")
    return Groq(api_key=api_key)


def analyze_with_llm(text: str) -> dict:
    """Return {"llm_score": float, "reasoning": str, "error": str|None}."""
    try:
        client = _get_client()
        response = client.chat.completions.create(
            model=MODEL,
            temperature=0,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        raw = response.choices[0].message.content.strip()
        match = _JSON_RE.search(raw)
        payload = json.loads(match.group(0) if match else raw)
        score = float(payload["ai_probability"])
        score = max(0.0, min(1.0, score))
        return {
            "llm_score": round(score, 4),
            "reasoning": payload.get("reasoning", ""),
            "error": None,
        }
    except Exception as exc:  # network error, bad key, malformed JSON, etc.
        return {"llm_score": 0.5, "reasoning": "", "error": str(exc)}
